name: Publish images to dockerhub
on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  docker:
    name: Build and publish docker images
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          # docker login
          docker version
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Identify git ref tags state
        id: tags
        uses: livepeer/action-gh-release-tags@latest

      - name: docker build & push
        run: make docker_ci "tags=${{ steps.tags.outputs.tags }}"

      - name: notify livepeer-infra
        run: curl -X POST https://holy-bread-207a.livepeer.workers.dev
