name: Publish new release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@master

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies
        run: |
          go mod download

      - name: Build analyzer binary
        run: |
          mkdir -p releases/ build/
          for platform in linux darwin windows
          do
            for arch in arm64 amd64
            do
              GOOS="$platform" GOARCH="$arch" make analyzer
              cd "build/"
              if [ "$platform" = "windows" ]
              then
                mv analyzer.exe livepeer-analyzer.exe
                zip -9 "../releases/livepeer-analyzer-${platform}-${arch}.zip" "livepeer-analyzer.exe"
              else
                mv analyzer livepeer-analyzer
                tar -czf "../releases/livepeer-analyzer-${platform}-${arch}.tar.gz" "livepeer-analyzer"
              fi
              cd -
            done
          done

      - name: Generate sha256 checksum and gpg signatures for release artifacts
        uses: livepeer/action-gh-checksum-and-gpg-sign@latest
        with:
          artifacts-dir: releases
          release-name: ${{ github.ref_name }}
          gpg-key: ${{ secrets.CI_GPG_SIGNING_KEY }}
          gpg-key-passphrase: ${{ secrets.CI_GPG_SIGNING_PASSPHRASE }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            releases/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
